_core:
  default_config_hash: XgeYJpPmZIOwE_nA73tYvFw-Rcj-HtlbNwfktqSVsaQ
langcode: cs
broker_url: 'tcp://tkaniny-devel.phil.muni.cz:61613'
jwt_expiry: '+2 hour'
upload_form_location: ''
upload_form_allowed_mimetypes: ''
gemini_url: ''
gemini_pseudo_bundles:
  'islandora_object:node': 'islandora_object:node'
  'audio:media': 'audio:media'
  'file:media': 'file:media'
  'image:media': 'image:media'
  'video:media': 'video:media'
delete_media_and_files: true
