entity_type_groups:
  node:
    fabric:
      basic: basic
      advanced: advanced
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
tag_trim_method: beforeValue
tag_trim_maxlength:
  metatag_maxlength_title: null
  metatag_maxlength_description: null
  metatag_maxlength_abstract: null
  metatag_maxlength_dcterms_title: null
  metatag_maxlength_dcterms_description: null
